{% set name = "airflow" %}
{% set version = "1.9.0" %}
{% set sha256 = "14fb16e9a10a829d71e7106f178e54436c24ae23681d9879f4a7e97739818556" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/apache/incubator-{{ name }}/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  skip: True  # [win or not py27]
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
  run:
    - python
    - alembic >=0.8.3,<0.9
    - bleach ==2.1.2
    - configparser >=3.5.0, <3.6.0
    - croniter >=0.3.17,<0.4
    - dill >=0.2.2,<0.3
    - flask >=0.11,<0.12
    - flask-admin ==1.4.1
    - flask-cache >=0.13.1,<0.14
    - flask-login ==0.2.11
    - flask-swagger ==0.2.13
    - flask-wtf 0.14.*
    - funcsigs ==1.0.0  # [py<33]
    - future >=0.16.0,<0.17
    - gitpython >=2.0.2
    - gunicorn >=19.4.0,<20.0
    - jinja2 >=2.7.3,<2.9.0
    - lxml >=3.6.0,<4.0
    - markdown >=2.5.2,<3.0
    - pandas >=0.17.1,<1.0.0
    - psutil >=4.2.0,<5.0.0
    - pygments >=2.0.1,<3.0
    - python-daemon >=2.1.1,<2.2
    - python-dateutil >=2.3,<3
    - python-nvd3 ==0.14.2
    - requests >=2.5.1,<3
    - setproctitle >=1.1.8,<2
    - sqlalchemy >=0.9.8
    - tabulate >=0.7.5,<0.8.0
    - thrift >=0.9.2
    - zope.deprecation >=4.0,<5.0

test:
  imports:
    - airflow
    - airflow.api
    - airflow.api.auth
    - airflow.api.auth.backend
    - airflow.api.client
    - airflow.api.common
    - airflow.api.common.experimental
    - airflow.bin
    - airflow.contrib
    - airflow.contrib.auth
    - airflow.contrib.auth.backends
    - airflow.contrib.executors
    - airflow.contrib.hooks
    - airflow.contrib.operators
    - airflow.contrib.sensors
    - airflow.contrib.task_runner
    - airflow.dag
    - airflow.example_dags
    - airflow.example_dags.subdags
    - airflow.executors
    - airflow.hooks
    - airflow.macros
    - airflow.migrations
    - airflow.migrations.versions
    - airflow.operators
    - airflow.security
    - airflow.task_runner
    - airflow.ti_deps
    - airflow.ti_deps.deps
    - airflow.utils
    - airflow.www
    - airflow.www.api
    - airflow.www.api.experimental

  commands:
    - airflow initdb

about:
  home: http://airflow.apache.org 
  license: Apache 2.0
  license_file: LICENSE
  summary: 'Airflow is a platform to programmatically author, schedule and monitor workflows'

  description: |
      Use airflow to author workflows as directed acyclic graphs (DAGs) of tasks. The airflow
      scheduler executes your tasks on an array of workers while following the specified
      dependencies. Rich command line utilities make performing complex surgeries on DAGs a
      snap. The rich user interface makes it easy to visualize pipelines running in
      production, monitor progress, and troubleshoot issues when needed.

      When workflows are defined as code, they become more maintainable, versionable,
      testable, and collaborative.

  doc_url: http://pythonhosted.org/airflow/profiling.html
  dev_url: https://github.com/apache/incubating-airflow

extra:
  recipe-maintainers:
    - sodre
