{% set name = "airflow" %}
{% set version = "1.9.0" %}
{% set sha256 = "14fb16e9a10a829d71e7106f178e54436c24ae23681d9879f4a7e97739818556" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/apache/incubator-{{ name }}/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  skip: True  # [win or not py27]
  number: 0
  script:
    - true

requirements:
  build:
    - python
    - pip
  run:
    - python
    - alembic >=0.8.3,<0.9
    - bleach ==2.1.2
    - configparser >=3.5.0, <3.6.0
    - croniter >=0.3.17,<0.4
    - dill >=0.2.2,<0.3
    - flask >=0.11,<0.12
    - flask-admin ==1.4.1
    - flask-cache >=0.13.1,<0.14
    - flask-login ==0.2.11
    - flask-swagger ==0.2.13
    - flask-wtf 0.14.*
    - funcsigs ==1.0.0  # [py<33]
    - future >=0.16.0,<0.17
    - gitpython >=2.0.2
    - gunicorn >=19.4.0,<20.0
    - jinja2 >=2.7.3,<2.9.0
    - lxml >=3.6.0,<4.0
    - markdown >=2.5.2,<3.0
    - pandas >=0.17.1,<1.0.0
    - psutil >=4.2.0,<5.0.0
    - pygments >=2.0.1,<3.0
    - python-daemon >=2.1.1,<2.2
    - python-dateutil >=2.3,<3
    - python-nvd3 ==0.14.2
    - requests >=2.5.1,<3
    - setproctitle >=1.1.8,<2
    - sqlalchemy >=0.9.8
    - tabulate >=0.7.5,<0.8.0
    - thrift >=0.9.2
    - zope.deprecation >=4.0,<5.0

test:
  imports:
    - airflow
    - airflow.api
    - airflow.api.auth
    - airflow.api.auth.backend
    - airflow.api.client
    - airflow.api.common
    - airflow.api.common.experimental
    - airflow.bin
    - airflow.contrib
    - airflow.contrib.auth
    - airflow.contrib.auth.backends
    - airflow.contrib.executors
    - airflow.contrib.hooks
    - airflow.contrib.operators
    - airflow.contrib.sensors
    - airflow.contrib.task_runner
    - airflow.dag
    - airflow.example_dags
    - airflow.example_dags.subdags
    - airflow.executors
    - airflow.hooks
    - airflow.macros
    - airflow.migrations
    - airflow.migrations.versions
    - airflow.operators
    - airflow.security
    - airflow.task_runner
    - airflow.ti_deps
    - airflow.ti_deps.deps
    - airflow.utils
    - airflow.www
    - airflow.www.api
    - airflow.www.api.experimental

  commands:
    - airflow initdb

outputs:
  - name: {{ name }}
    script: {{ name }}-build.sh
    requirements:
      build:
        - python
        - pip
      run:
        - python
        - alembic >=0.8.3,<0.9
        - bleach ==2.1.2
        - configparser >=3.5.0, <3.6.0
        - croniter >=0.3.17,<0.4
        - dill >=0.2.2,<0.3
        - flask >=0.11,<0.12
        - flask-admin ==1.4.1
        - flask-cache >=0.13.1,<0.14
        - flask-login ==0.2.11
        - flask-swagger ==0.2.13
        - flask-wtf 0.14.*
        - funcsigs ==1.0.0  # [py<33]
        - future >=0.16.0,<0.17
        - gitpython >=2.0.2
        - gunicorn >=19.4.0,<20.0
        - jinja2 >=2.7.3,<2.9.0
        - lxml >=3.6.0,<4.0
        - markdown >=2.5.2,<3.0
        - pandas >=0.17.1,<1.0.0
        - psutil >=4.2.0,<5.0.0
        - pygments >=2.0.1,<3.0
        - python-daemon >=2.1.1,<2.2
        - python-dateutil >=2.3,<3
        - python-nvd3 ==0.14.2
        - requests >=2.5.1,<3
        - setproctitle >=1.1.8,<2
        - sqlalchemy >=0.9.8
        - tabulate >=0.7.5,<0.8.0
        - thrift >=0.9.2
        - zope.deprecation >=4.0,<5.0

  - name: {{ name }}-with-async
    requirements:
      run:
        - {{ name }}
        - greenlet >=0.4.9
        - evenlet >=0.9.7
        - gevent >=0.13

  - name: {{ name }}-with-azure
    requirements:
      run:
        - {{ name }}
        - azure-storage >=0.34.0

  - name: {{ name }}-with-celery
    requirements:
      run:
        - {{ name }}
        - celery >=4.0.0
        - flower >=0.7.3

  - name: {{ name }}-with-cloudant
    requirements:
      run:
        - {{ name }}
        - cloudant >=0.5.9,<2.0

  - name: {{ name }}-with-crypto
    requirements:
      run:
        - {{ name }}
        - cryptography >=0.9.3

  - name: {{ name }}-with-dask
    requirements:
      run:
        - {{ name }}
        - distributed >=1.15.2,<2

  - name: {{ name }}-with-databricks
    requirements:
      run:
        - {{ name }}
        - requests >=2.5.1,<3

  - name: {{ name }}-with-datadog
    requirements:
      run:
        - {{ name }}
        - datadog >=0.14.0

  - name: {{ name }}-with-docker
    requirements:
      run:
        - {{ name }}
        - docker-py >=1.6.0

  - name: {{ name }}-with-emr
    requirements:
      run:
        - {{ name }}
        - boto3 >=1.0.0

  - name: {{ name }}-with-gcp_api
    requirements:
      run:
        - {{ name }}
        - httplib2
        - google-api-python-client >=1.5.0,<1.6.0
        - oauth2client >=2.0.2,<2.1.0
        - pyopenssl
        - google-cloud-dataflow
        - pandas-gbq

  - name: {{ name }}-with-github_enterprise
    requirements:
      run:
        - flask-oauthlib >=0.9.1

  - name: {{ name }}-with-hdfs
    requirements:
      run:
        - {{ name }}
        - snakebite >=2.7.8

  - name: {{ name }}-with-hive
    requirements:
      run:
        - {{ name }}
        - hive-thrift-py >=0.0.1
        - pyhive >=0.1.3
        - impyla >=0.13.3
        - unicodecsv >=0.14.1

  - name: {{ name }}-with-jira
    requirements:
      run:
        - {{ name }}
        - jira >=1.0.7

  # We are missing python-krbv and apple/kerberos
  #- name: {{ name }}-with-kerberos
  #  requirements:
  #    run:
  #      - {{ name }}
  #      - pykerberos >=1.1.13
  #      - requests-kerberos >=0.10.0
  #      - thrift_sasl >=0.2.0
  #      - sasl
  #      - python-krbv
  #      - kerberos >=1.2.5

  - name: {{ name }}-with-ldap
    requirements:
      run:
        - {{ name }}
        - ldap3 >=0.9.9.1

  - name: {{ name }}-with-mssql
    requirements:
      run:
        - {{ name }}
        - pymssql >=2.1.1
        - unicodecsv >=0.14.1

  #- name: {{ name }}-with-mysql
  #  requirements:
  #    run:
  #      - {{ name }}
  #      - mysqlclient >=1.3.6

  #- name: {{ name }}-with-oracle
  #  requirements:
  #    run:
  #      - {{ name }}
  #      - cx_oracle>=5.1.2

  - name: {{ name }}-with-password
    requirements:
      run:
        - {{ name }}
        - bcrypt >=2.0.0
        - flask-bcrypt >=0.7.1

  - name: {{ name }}-with-postgres
    requirements:
      run:
        - {{ name }}
        - psycopg2 >=2.7.1

  - name: {{ name }}-with-qds
    requirements:
      run:
        - {{ name }}
        - qds-sdk>=1.9.6

  - name: {{ name }}-with-rabbitmq
    requirements:
      run:
        - {{ name }}
        - librabbitmq >=1.6.1

  - name: {{ name }}-with-redis
    requirements:
      run:
        - {{ name }}
        - redis-py >=2.10.5

  - name: {{ name }}-with-s3
    requirements:
      run:
        - {{ name }}
        - boto >=2.36.0
        - filechunkio >=1.6

  - name: {{ name }}-with-samba
    requirements:
      run:
        - {{ name }}
        - pysmbclient >=0.1.3
        - filechunkio >=1.6

  - name: {{ name }}-with-salesforce
    requirements:
      run:
        - {{ name }}
        - simple-salesforce >=0.72

  - name: {{ name }}-with-slack
    requirements:
      run:
        - {{ name }}
        - slackclient >=1.0.0

  - name: {{ name }}-with-ssh
    requirements:
      run:
        - {{ name }}
        - paramiko >=2.1.1

  - name: {{ name }}-with-statsd
    requirements:
      run:
        - {{ name }}
        - statsd >=3.0.1,<4.0

  - name: {{ name }}-with-vertica
    requirements:
      run:
        - {{ name }}
        - vertica-python >=0.5.1

  - name: {{ name }}-with-webhdfs
    requirements:
      run:
        - {{ name }}
        - python-hdfs >=0.5.1

about:
  home: http://airflow.apache.org 
  license: Apache 2.0
  license_file: LICENSE
  summary: 'Airflow is a platform to programmatically author, schedule and monitor workflows'

  description: |
      Use airflow to author workflows as directed acyclic graphs (DAGs) of tasks. The airflow
      scheduler executes your tasks on an array of workers while following the specified
      dependencies. Rich command line utilities make performing complex surgeries on DAGs a
      snap. The rich user interface makes it easy to visualize pipelines running in
      production, monitor progress, and troubleshoot issues when needed.

      When workflows are defined as code, they become more maintainable, versionable,
      testable, and collaborative.

  doc_url: http://pythonhosted.org/airflow/profiling.html
  dev_url: https://github.com/apache/incubating-airflow

extra:
  recipe-maintainers:
    - sodre
